# basic options
title: Kampeervakantie September 2017
author: Kees
email: your-email@domain.com
description: Blog van de vakantie
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
