# basic options
title: Kampeervakantie September 2017
author: Kees
description: Blog van de kampeervakantie langs de Franse kust.
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
