# basic options
title: Vakantie September 2017
author: Teksten geschreven door Kees
email: Website gemaakt door Kees
description: Verslag van de vakantie

# Build settings
markdown: kramdown
theme: minima
